repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.3.2
    hooks:
      - id: poetry-check
        name: ğŸ“œ Check pyproject with Poetry
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: âœ… Check JSON files
        exclude: .devcontainer
      - id: check-toml
        name: âœ… Check TOML files
      - id: check-yaml
        name: âœ… Check YAML files
      - id: check-added-large-files
        name: ğŸ“ Check for large files
      - id: debug-statements
        name: ğŸ› Check for forgotten debug statemens
      - id: check-symlinks
        name: ğŸ”— Check for broken symlinks
      - id: check-merge-conflict
        name: ğŸ’¥ Check for merge conflicts
      - id: end-of-file-fixer
        name: ğŸ”š Fix End of Files
      - id: trailing-whitespace
        name: â¬œ Fix trailing whitespaces
        exclude_types: [text]
      - id: requirements-txt-fixer
        name: ğŸ“ Fix requirements.txt
      - id: no-commit-to-branch
        name: ğŸ›‘ Don't commit to main branch
        args:
          - --branch=master
          - --branch=main
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        name: ğŸ¶ Ruff Linter
        args:
          - --fix
      - id: ruff-format
        name: ğŸ¶ Ruff Formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: ğŸ¨ Format using prettier
